{
	"routers":[
			{
				"linkTo":"/qa/两会",
				"key":"qa",
				"title":"两会",
				"isIcon":true,
				"type":"question-circle-o",
			},{
				"linkTo":"/puzzle/",
				"key":"puzzle",
				"title":"拼图",
				"isIcon":true,
				"type":"picture"
			}
	]
}