{
	"routers":[
			{
				"linkTo":"/",
				"key":"zmiti",
				"title":"微场景",
				"isIcon":true,
				"type":"mobile",
				"isShow":true
			},{
				"linkTo":"/qa/",
				"key":"qa",
				"title":"微问答",
				"isIcon":true,
				"type":"question-circle-o",
				"isShow":true
			},{
				"linkTo":"/richimg/",
				"key":"richimg",
				"title":"富图片",
				"isIcon":true,
				"type":"picture",
				"isShow":true
			},{
				"linkTo":"/puzzle/",
				"key":"puzzle",
				"title":"拼图",
				"isIcon":true,
				"type":"picture",
				"isShow":true
			}
	]
}